language: node_js
node_js:
    - "6.1"
sudo: required
addons:
  chrome: stable
before_script:
    - cd player
    - npm install
    - npm run build-preview sunbird
    - grunt compress:preview
    - grunt generate-libs
    - grunt build-jsdoc

script:
    - grunt renderer-test